[package]
name = "gstuff"
version = "0.2.0"
authors = ["ArtemGr <artemciy@gmail.com>"]

description = "Small macro and trinkets that make my life easier."
repository = "https://github.com/ArtemGr/gstuff.rs"
license = "MIT"

[lib]
name = "gstuff"
path = "gstuff.rs"
doctest = false

[dependencies]
lazy_static = "0.2"
libc = "0.2"
term = "0.4"
term_size = "0.2"
