[package]
name = "gstuff"
version = "0.1.0"
authors = ["ArtemGr <artemciy@gmail.com>"]

description = "Small macro and trinkets that make my life easier."
repository = "https://github.com/ArtemGr/gstuff.rs"
license = "MIT"

[lib]
name = "gstuff"
path = "gstuff.rs"
doctest = false
