[package]
name = "gstuff"
version = "0.6.6"
edition = "2018"
authors = ["ArtemGr <artemciy@gmail.com>"]

description = "Small macro and trinkets that make my life easier."
documentation = "https://docs.rs/gstuff/"
repository = "https://github.com/ArtemGr/gstuff.rs"
license = "MIT"

[lib]
name = "gstuff"
path = "gstuff.rs"
doctest = false

[features]
nightly = ["atomic/nightly"]
base62 = ["num-bigint", "num-traits", "smallvec"]
base91 = ["smallvec"]
rdtsc = []

[dependencies]
atomic = "0.4"
lazy_static = "1"
libc = "0.2"
num-bigint = {version = "0.2", optional = true}
num-traits = {version = "0.2", optional = true}
smallvec = {version = "1.3", optional = true, features = ["const_generics", "union", "write"]}
term = {version = "0.6", optional = true}
term_size = {version = "0.3", optional = true}
